In [271]:
import pandas as pd 
import numpy as np

In [272]:
df = pd.read_csv('/Users/thananpornsethjinda/Desktop/internship/projects/in-progress/student-performance-classification/data/DATA (1).csv')

In [273]:
processed = df.copy()

In [274]:
column_info = {
    'STUDENT ID':'id',
    '1': 'student_age',
    '2': 'sex',
    '3': 'high_school_type',
    '4': 'scholarship_type',
    '5': 'additional_work',
    '6': 'artistic_sports_activity',
    '7': 'has_partner',
    '8': 'salary',
    '9': 'transportation',
    '10': 'accommodation_type',
    '11': 'mother_education',
    '12': 'father_education',
    '13': 'siblings',
    '14': 'parental_status',
    '15': 'mother_occupation',
    '16': 'father_occupation',
    '17': 'weekly_study_hours',
    '18': 'reading_freq_non_sci',
    '19': 'reading_freq_sci',
    '20': 'seminar_attendance',
    '21': 'project_impact',
    '22': 'class_attendance',
    '23': 'prep_midterm_1',
    '24': 'prep_midterm_2',
    '25': 'note_taking',
    '26': 'listening_in_class',
    '27': 'discussion_interest',
    '28': 'flip_classroom',
    '29': 'last_semester_gpa',
    '30': 'expected_gpa',
    'COURSE ID': 'course_id',
    'GRADE': 'output_grade'
}

In [275]:
processed.columns = processed.columns.map(column_info)

In [276]:
processed

id  student_age  sex  high_school_type  scholarship_type  \
0      STUDENT1            2    2                 3                 3   
1      STUDENT2            2    2                 3                 3   
2      STUDENT3            2    2                 2                 3   
3      STUDENT4            1    1                 1                 3   
4      STUDENT5            2    2                 1                 3   
..          ...          ...  ...               ...               ...   
140  STUDENT141            2    1                 2                 3   
141  STUDENT142            1    1                 2                 4   
142  STUDENT143            1    1                 1                 4   
143  STUDENT144            2    1                 2                 4   
144  STUDENT145            1    1                 1                 5   

     additional_work  artistic_sports_activity  has_partner  salary  \
0                  1                         2            2       1   
1                  1                         2            2       1   
2                  2                         2            2       2   
3                  1                         2            1       2   
4                  2                         2            1       3   
..               ...                       ...          ...     ...   
140                1                         1            2       1   
141                2                         2            2       1   
142                2                         2            2       1   
143                1                         1            1       5   
144                2                         2            2       3   

     transportation  ...  prep_midterm_1  prep_midterm_2  note_taking  \
0                 1  ...               1               1            3   
1                 1  ...               1               1            3   
2                 4  ...               1               1            2   
3                 1  ...               1               2            3   
4                 1  ...               2               1            2   
..              ...  ...             ...             ...          ...   
140               1  ...               1               1            2   
141               4  ...               1               1            3   
142               1  ...               1               1            3   
143               2  ...               2               1            2   
144               1  ...               2               1            3   

     listening_in_class  discussion_interest  flip_classroom  \
0                     2                    1               2   
1                     2                    3               2   
2                     2                    1               1   
3                     2                    2               1   
4                     2                    2               1   
..                  ...                  ...             ...   
140                   1                    2               1   
141                   2                    2               1   
142                   3                    2               1   
143                   1                    2               1   
144                   2                    3               1   

     last_semester_gpa  expected_gpa  course_id  output_grade  
0                    1             1          1             1  
1                    2             3          1             1  
2                    2             2          1             1  
3                    3             2          1             1  
4                    2             2          1             1  
..                 ...           ...        ...           ...  
140                  3             3          9             5  
141                  5             3          9             5  
142                  4             3          9             1

In [277]:
sex = {
    1:'female', 
    2:'male'
}

has_partner = {1: 'yes', 2: 'no'}

parental_status = {1: 'married', 2: 'divorced', 3: 'died - one of them or both'}

high_school_type = {1: 'private', 2: 'state', 3: 'other'}

additional_work = {1: 'yes', 2: 'no'}

artistic_sports_activity = {1: 'yes', 2: 'no'}


In [278]:
processed['sex'] = processed['sex'].map(sex)

processed['has_partner'] = processed['has_partner'].map(has_partner)

processed['parental_status'] = processed['parental_status'].map(parental_status)

processed['high_school_type'] = processed['high_school_type'].map(high_school_type)

processed['additional_work'] = processed['additional_work'].map(additional_work)

processed['artistic_sports_activity'] = processed['artistic_sports_activity'].map(artistic_sports_activity)


In [279]:
mother_occupation = {1: 'retired', 2: 'housewife', 3: 'government officer', 4: 'private sector employee', 5: 'self-employment', 6: 'other'}

father_occupation = {1: 'retired', 2: 'government officer', 3: 'private sector employee', 4: 'self-employment', 5: 'other'}

processed['mother_occupation'] = processed['mother_occupation'].map(mother_occupation)

processed['mother_occupation'] = processed['mother_occupation'].map(mother_occupation)


In [280]:

seminar_attendance = {1: 'Yes', 2: 'No'}

processed['seminar_attendance'] = processed['seminar_attendance'].map(seminar_attendance)


In [281]:
transportation = {1: 'bus', 2: 'private car/taxi', 3: 'bicycle', 4: 'other'}

processed['transportation'] = processed['transportation'].map(transportation)

In [282]:
flip_classroom = {1: 'not_useful', 2: 'useful', 3: 'not_applicable'}

processed['flip_classroom'] = processed['flip_classroom'].map(flip_classroom)

In [283]:
prep_midterm_1 = {1: 'alone', 2: 'with_friends', 3: 'not_applicable'}
prep_midterm_2 = {1: 'close', 2: 'regular', 3: 'never'}

processed['prep_midterm_1'] = processed['prep_midterm_1'].map(prep_midterm_1)

processed['prep_midterm_2'] = processed['prep_midterm_2'].map(prep_midterm_2)

In [284]:
processed

id  student_age     sex high_school_type  scholarship_type  \
0      STUDENT1            2    male            other                 3   
1      STUDENT2            2    male            other                 3   
2      STUDENT3            2    male            state                 3   
3      STUDENT4            1  female          private                 3   
4      STUDENT5            2    male          private                 3   
..          ...          ...     ...              ...               ...   
140  STUDENT141            2  female            state                 3   
141  STUDENT142            1  female            state                 4   
142  STUDENT143            1  female          private                 4   
143  STUDENT144            2  female            state                 4   
144  STUDENT145            1  female          private                 5   

    additional_work artistic_sports_activity has_partner  salary  \
0               yes                       no          no       1   
1               yes                       no          no       1   
2                no                       no          no       2   
3               yes                       no         yes       2   
4                no                       no         yes       3   
..              ...                      ...         ...     ...   
140             yes                      yes          no       1   
141              no                       no          no       1   
142              no                       no          no       1   
143             yes                      yes         yes       5   
144              no                       no          no       3   

       transportation  ...  prep_midterm_1  prep_midterm_2  note_taking  \
0                 bus  ...           alone           close            3   
1                 bus  ...           alone           close            3   
2               other  ...           alone           close            2   
3                 bus  ...           alone         regular            3   
4                 bus  ...    with_friends           close            2   
..                ...  ...             ...             ...          ...   
140               bus  ...           alone           close            2   
141             other  ...           alone           close            3   
142               bus  ...           alone           close            3   
143  private car/taxi  ...    with_friends           close            2   
144               bus  ...    with_friends           close            3   

     listening_in_class discussion_interest flip_classroom  last_semester_gpa  \
0                     2                   1         useful                  1   
1                     2                   3         useful                  2   
2                     2                   1     not_useful                  2   
3                     2                   2     not_useful                  3   
4                     2                   2     not_useful                  2   
..                  ...                 ...            ...                ...   
140                   1                   2     not_useful                  3   
141                   2                   2     not_useful                  5   
142                   3                   2     not_useful                  4   
143                   1                   2     not_useful                  5   
144                   2                   3     not_useful                  5   

     expected_gpa  course_id  output_grade  
0               1          1             1  
1               3          1             1  
2               2          1             1  
3               2          1             1  
4               2          1             1  
..            ...        ...           ...  
140             3          9             5  
141             3          9             5  
142             

In [285]:
class_attendance = {1: 3, 2:2, 3:1}

processed['class_attendance'] = processed['class_attendance'].map(class_attendance)

In [286]:
accommodation_type = {1: 'rental', 2: 'dormitory', 3: 'with_family', 4: 'other'}

processed['accommodation_type'] = processed['accommodation_type'].map(accommodation_type)

In [287]:
project_impact = {
    1:3,
    2:1,
    3:2
}

processed['project_impact'] = processed['project_impact'].map(project_impact)

In [288]:
processed['output_grade'].astype('object')

0      1
1      1
2      1
3      1
4      1
      ..
140    5
141    5
142    1
143    4
144    3
Name: output_grade, Length: 145, dtype: object

In [289]:
processed_final = processed.copy().drop(['course_id', 'id'], axis=1)

In [290]:
processed_final.select_dtypes(include=np.number).columns.to_list()

['student_age',
 'scholarship_type',
 'salary',
 'mother_education',
 'father_education',
 'siblings',
 'father_occupation',
 'weekly_study_hours',
 'reading_freq_non_sci',
 'reading_freq_sci',
 'project_impact',
 'class_attendance',
 'note_taking',
 'listening_in_class',
 'discussion_interest',
 'last_semester_gpa',
 'expected_gpa',
 'output_grade']

In [291]:
y = processed_final['output_grade']

X = processed_final[processed_final.columns[:-1]]

In [292]:
from sklearn.model_selection import train_test_split

X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.2222222222, random_state=42, stratify=y_train_val)

In [293]:
ORDINAL_COLUMNS = X_train.select_dtypes(include=np.number).columns.to_list()

CATEGORICAL_COLUMNS = X_train.select_dtypes(include=('object')).columns.to_list()

In [294]:
CATEGORICAL_COLUMNS


['sex',
 'high_school_type',
 'additional_work',
 'artistic_sports_activity',
 'has_partner',
 'transportation',
 'accommodation_type',
 'parental_status',
 'mother_occupation',
 'seminar_attendance',
 'prep_midterm_1',
 'prep_midterm_2',
 'flip_classroom']

In [295]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(drop='first', handle_unknown='ignore')

enc.fit(X_train[CATEGORICAL_COLUMNS])

ENCODED_COLUMNS = list(enc.get_feature_names_out(CATEGORICAL_COLUMNS))

In [296]:
X_train[ENCODED_COLUMNS] = enc.transform(X_train[CATEGORICAL_COLUMNS]).toarray()

X_val[ENCODED_COLUMNS] = enc.transform(X_val[CATEGORICAL_COLUMNS]).toarray()


/Users/thananpornsethjinda/miniconda3/envs/grass/lib/python3.13/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [6] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(


In [297]:
X_test[ENCODED_COLUMNS] = enc.transform(X_test[CATEGORICAL_COLUMNS]).toarray()

In [298]:
X_train_final = X_train.copy()[ORDINAL_COLUMNS + ENCODED_COLUMNS]

X_val_final = X_val.copy()[ORDINAL_COLUMNS + ENCODED_COLUMNS]

X_test_final = X_test.copy()[ORDINAL_COLUMNS + ENCODED_COLUMNS]

In [299]:
from sklearn.metrics import confusion_matrix, roc_auc_score, f1_score

def train_and_validate(model, X_train=X_train_final, X_val=X_val_final, y_train=y_train, y_val=y_val): 
    model.fit(X_train, y_train)
    y_train_preds = model.predict(X_train)
    y_train_prob = model.predict_proba(X_train)
    y_val_preds = model.predict(X_val)
    y_val_prob = model.predict_proba(X_val)
    # Training metrics  
    print('Training Metrics')
    print(f'F1 Score:{f1_score(y_train, y_train_preds, average='weighted')}')

    print(f'{confusion_matrix(y_train, y_train_preds, normalize='true')}')

    print(f'ROC:{roc_auc_score(y_train, y_train_prob, multi_class='ovr')}')


    print('--' * 30)

    # Validation metrics 

    print('Validation Metrics')
    print(f'F1 Score:{f1_score(y_val, y_val_preds, average='weighted')}')

    print(f'{confusion_matrix(y_val, y_val_preds, normalize='true')}')

    print(f'ROC:{roc_auc_score(y_val, y_val_prob, multi_class='ovr')}')

In [300]:
from sklearn.ensemble import GradientBoostingClassifier

bgc = GradientBoostingClassifier(learning_rate=0.011563640674119394, max_depth=1, n_estimators=158)

train_and_validate(bgc)

Training Metrics
F1 Score:0.5076179595981576
[[0.2        0.8        0.         0.         0.         0.
  0.         0.        ]
 [0.         0.91666667 0.04166667 0.04166667 0.         0.
  0.         0.        ]
 [0.         0.35294118 0.64705882 0.         0.         0.
  0.         0.        ]
 [0.         0.4        0.06666667 0.53333333 0.         0.
  0.         0.        ]
 [0.         0.42857143 0.28571429 0.         0.14285714 0.14285714
  0.         0.        ]
 [0.         0.33333333 0.08333333 0.         0.         0.41666667
  0.         0.16666667]
 [0.         0.44444444 0.11111111 0.11111111 0.         0.33333333
  0.         0.        ]
 [0.         0.41666667 0.         0.         0.         0.
  0.         0.58333333]]
ROC:0.8934617094484586
------------------------------------------------------------
Validation Metrics
F1 Score:0.22216748768472908
[[0.         0.5        0.5        0.         0.         0.
  0.         0.        ]
 [0.         0.71428571 0.1428571

In [301]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

train_and_validate(rfc)

Training Metrics
F1 Score:1.0
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
ROC:1.0
------------------------------------------------------------
Validation Metrics
F1 Score:0.18357487922705315
[[0.         0.5        0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.57142857 0.14285714 0.14285714 0.         0.
  0.14285714 0.        ]
 [0.         0.6        0.4        0.         0.         0.
  0.         0.        ]
 [0.         0.25       0.5        0.25       0.         0.
  0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.66666667 0.         0.33333333 0.         0.
  0.         0.        ]
 [0.         0.         0.         0.33333333 0.         0.
  0.         0.66666667]
 [0.         1.         0.         0.    

In [302]:
# fine tuning 

from sklearn.model_selection import RandomizedSearchCV

from sklearn.model_selection import GridSearchCV

from scipy.stats import randint, uniform

param_grid = {
    'learning_rate': uniform(0.01, 0.1),
    'n_estimators': randint(30, 300),
    'max_depth': randint(1, 9)
}

rsv = RandomizedSearchCV(bgc, param_distributions=param_grid, n_iter=50, n_jobs=-1, random_state=42)

rsv.fit(X_train_final, y_train)


RandomizedSearchCV(estimator=GradientBoostingClassifier(learning_rate=0.011563640674119394,
                                                        max_depth=1,
                                                        n_estimators=158),
                   n_iter=50, n_jobs=-1,
                   param_distributions={'learning_rate': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x1372d3d90>,
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x1373745f0>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x13633c450>},
                   random_state=42)

In [303]:
rsv.best_params_

{'learning_rate': np.float64(0.011563640674119394),
 'max_depth': 1,
 'n_estimators': 158}

In [304]:
rf_param_grid = {
    'n_estimators': randint(50, 400), 
    'max_depth': randint(1, 60),
    'min_samples_split': (2, 100),
    'min_samples_leaf': (1, 100),
}

rsv_rf = RandomizedSearchCV(rfc, param_distributions=rf_param_grid, n_iter=50, n_jobs=-1, random_state=42)

rsv_rf.fit(X_train_final, y_train)

RandomizedSearchCV(estimator=RandomForestClassifier(), n_iter=50, n_jobs=-1,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x13788e890>,
                                        'min_samples_leaf': (1, 100),
                                        'min_samples_split': (2, 100),
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x133806c60>},
                   random_state=42)

In [305]:
rsv_rf.best_params_

{'max_depth': 32,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 101}

In [306]:
tuned_rfc = RandomForestClassifier(n_estimators= 356, max_depth= 57, min_samples_leaf= 1, min_samples_split=2, random_state=42)

train_and_validate(tuned_rfc)

Training Metrics
F1 Score:1.0
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]
ROC:1.0
------------------------------------------------------------
Validation Metrics
F1 Score:0.22681150267357167
[[0.         0.5        0.         0.5        0.         0.
  0.         0.        ]
 [0.         0.28571429 0.42857143 0.14285714 0.         0.14285714
  0.         0.        ]
 [0.         0.4        0.6        0.         0.         0.
  0.         0.        ]
 [0.         0.25       0.5        0.25       0.         0.
  0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.66666667 0.         0.33333333 0.         0.
  0.         0.        ]
 [0.         0.33333333 0.         0.         0.         0.
  0.         0.66666667]
 [0.         0.         0.       

In [307]:

def ROC(model, X_train=X_train_final, X_val=X_val_final, y_train=y_train, y_val=y_val): 
    
    model.fit(X_train, y_train)

    y_val_prob = model.predict_proba(X_val)

    return roc_auc_score(y_val, y_val_prob, multi_class='ovr')

In [317]:
import optuna

from optuna import Trial

def objective(trial: Trial): 

    n_estimators = trial.suggest_int('n_estimators', 300, 400)
    
    max_depth = trial.suggest_int('max_depth', 50, 70)
    
    min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 4)

    min_sample_split = trial.suggest_int('min_samples_split',2, 4)

    model = RandomForestClassifier(

        n_estimators=n_estimators,

        max_depth=max_depth,

        min_samples_leaf=min_samples_leaf,

        min_samples_split=min_sample_split,

        random_state=42

    )

    score = ROC(model)

    return score

    


In [318]:
study = optuna.create_study(direction='maximize')

[I 2025-09-08 22:24:55,259] A new study created in memory with name: no-name-d07c8024-c3b1-4917-afd4-cde0cfbe17e2


In [319]:
study.optimize(objective, n_trials=40)

[I 2025-09-08 22:24:57,414] Trial 0 finished with value: 0.6913851657601658 and parameters: {'n_estimators': 313, 'max_depth': 59, 'min_samples_leaf': 2, 'min_samples_split': 2}. Best is trial 0 with value: 0.6913851657601658.
[I 2025-09-08 22:24:57,672] Trial 1 finished with value: 0.6671589059089059 and parameters: {'n_estimators': 326, 'max_depth': 66, 'min_samples_leaf': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.6913851657601658.
[I 2025-09-08 22:24:57,940] Trial 2 finished with value: 0.6591252728752728 and parameters: {'n_estimators': 318, 'max_depth': 64, 'min_samples_leaf': 3, 'min_samples_split': 4}. Best is trial 0 with value: 0.6913851657601658.
[I 2025-09-08 22:24:58,372] Trial 3 finished with value: 0.6679059366559367 and parameters: {'n_estimators': 399, 'max_depth': 60, 'min_samples_leaf': 4, 'min_samples_split': 2}. Best is trial 0 with value: 0.6913851657601658.
[I 2025-09-08 22:24:58,672] Trial 4 finished with value: 0.7426335007585008 and parameters: 

In [320]:
study.best_params

{'n_estimators': 381,
 'max_depth': 52,
 'min_samples_leaf': 1,
 'min_samples_split': 4}

In [312]:
def test(model, X_train=X_train_final, X_test=X_test_final, y_train=y_train, y_test=y_test): 
    
    model.fit(X_train, y_train)

    y_test_prob = model.predict_proba(X_test)

    return roc_auc_score(y_test, y_test_prob, multi_class='ovr')

In [321]:
## FINAL MODEL 

final_rfc = RandomForestClassifier(
    n_estimators=381,
    max_depth=52,
    min_samples_leaf=1,
    min_samples_split=4
)

train_and_validate(final_rfc)



Training Metrics
F1 Score:0.9900058241118229
[[1.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         1.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         1.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         1.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         1.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         1.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.11111111
  0.88888889 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         1.        ]]
ROC:0.9998829588014981
------------------------------------------------------------
Validation Metrics
F1 Score:0.161218092252575
[[0.         0.5        0.5        0.         0.         0.
  0.         0.        ]
 [0.         0.42857143 0.28571429 0.28571429 0.   

In [314]:
test(final_rfc)

np.float64(0.6486013986013985)

In [ ]:
## OKAY THIS IS THE FINAL MODEL done without CV 